### ISSUE TITLE
"Can't set headers after they are sent"

### ISSUE THREAD

**Issue by stevage** [jczaplew/csv-express#15]
My code looks like this:

```js
    twit.get('search/tweets', req.query, function(err, response) {
        const out = response.statuses.map(s => ({
            user_id: s.user.id,
            user_name: s.user.name,
            user_screen_name: s.user.screen_name,
            text: s.text,
        }));
        res.csv(out, true);
    });
```

It fails on the `res.csv` line like this:

```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (code/node_modules/express/lib/response.js:771:10)
    at ServerResponse.res.csv (code/node_modules/csv-express/lib/csv-express.js:68:8)
    at code/routes/index.js:78:13
    at Request._callback (code/node_modules/twitter/lib/twitter.js:227:5)
    at Request.self.callback (code/node_modules/twitter/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (code/node_modules/twitter/node_modules/request/request.js:1161:10)
```

```
    "csv-express": "^1.2.2",
    "express": "^4.15.2",
```

**Comment by stevage** [comment]
Never mind, something was pre-setting the response type as json.
